[project]
name = "wiyo-app"
version = "0.1.0"
description = "Anonymous Polling Application"
dependencies = [
    "pytest>=8.3.3",
    "pytest-cov>=5.0.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --tb=short"
