"""Add description to ForumPost

Revision ID: d0c1e6d9237c
Revises: 966ee5623d5b
Create Date: 2024-10-21 00:32:43.678837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c1e6d9237c'
down_revision = '966ee5623d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('comment_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.drop_column('comment_count')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
